// @ts-check
import eslintPluginJsonc from 'eslint-plugin-jsonc'

export default [
  ...eslintPluginJsonc.configs['flat/recommended-with-jsonc'],
  ...eslintPluginJsonc.configs['flat/recommended-with-json5'],
  {
    files: ['package.json'],
    rules: {
      'jsonc/sort-keys': ['error',
        {
          pathPattern: '^$',
          order: ['name',
            'version',
            'description',
            'private',
            'packageManager',
            'author',
            'type',
            'main',
            'exports',
            'license',
            'files',
            'bin',
            'scripts',
            'funding',
            'homepage',
            'repository',
            'bugs',
            'keywords',
            'categories',
            'dependencies',
            'devDependencies',
            'peerDependencies',
            'peerDependenciesMeta',
            'optionalDependencies',
            'sideEffects',
            'module',
            'unpkg',
            'jsdelivr',
            'types',
            'typesVersions',
            'icon',
            'engines',
            'activationEvents',
            'contributes',
            'pnpm',
            'overrides',
            'resolutions',
            'husky',
            'simple-git-hooks',
            'lint-staged',
            'eslintConfig',
          ],
        },
        {
          pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies$',
          order: { type: 'asc' },
        },
      ],
    },
  },
]
